version: '3.8'

services:
  web-dev:
    build: .
    ports:
      - "9001:80"
    restart: always
    
  web-prod:
    build: .
    ports:
      - "9002:80"
    restart: always

  my-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mypassword
     Volumes:  
    # تلاحظ# ربط مجلد بيانات قاعدة البيانات بمجلد وهمي (Volume) لضمان عدم ضياعها
      - postgres_data:/var/lib/postgresql/data

# تعريف الـ Volume في نهاية الملف ليتم إنشاؤه بواسطة Docker
volumes:
  postgres_data: أننا لم نضع ports لـ Postgres لأننا نريد حمايتها داخل الشبكة فقط
